// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiAFqrIp_qvDuShNMzhdAO5uh60xb2n0w',
    appId: '1:380916275111:web:69e1e8d97cb490bf52c882',
    messagingSenderId: '380916275111',
    projectId: 'pmjournalbase',
    authDomain: 'pmjournalbase.firebaseapp.com',
    storageBucket: 'pmjournalbase.firebasestorage.app',
    measurementId: 'G-CL3P221N2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4VFcKIulsWycM8Og4EL43B2TfXMQgho',
    appId: '1:380916275111:android:092422dd934e517952c882',
    messagingSenderId: '380916275111',
    projectId: 'pmjournalbase',
    storageBucket: 'pmjournalbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYYUUtrUdKwSe1A-2xU5Ef8rLYRaPe73Q',
    appId: '1:380916275111:ios:438e915593d01b3e52c882',
    messagingSenderId: '380916275111',
    projectId: 'pmjournalbase',
    storageBucket: 'pmjournalbase.firebasestorage.app',
    iosBundleId: 'com.example.pmJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYYUUtrUdKwSe1A-2xU5Ef8rLYRaPe73Q',
    appId: '1:380916275111:ios:438e915593d01b3e52c882',
    messagingSenderId: '380916275111',
    projectId: 'pmjournalbase',
    storageBucket: 'pmjournalbase.firebasestorage.app',
    iosBundleId: 'com.example.pmJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiAFqrIp_qvDuShNMzhdAO5uh60xb2n0w',
    appId: '1:380916275111:web:34e6300d8ed801dc52c882',
    messagingSenderId: '380916275111',
    projectId: 'pmjournalbase',
    authDomain: 'pmjournalbase.firebaseapp.com',
    storageBucket: 'pmjournalbase.firebasestorage.app',
    measurementId: 'G-M0FJDGY2X9',
  );
}
